name: Discord Log

on:
  workflow_run: # fallback to catch any workflow run status
    workflows: ["*"]
    types:
      - completed
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Send Discord notification
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.QU_SECURITY_DISCORD_WEBHOOK_URL }}
          message: |
            âœ… **GitHub Event Notification**

            ğŸ“Œ **Event:** `${{ github.event_name }}`
            ğŸ“‚ **Repository:** `${{ github.repository }}`
            ğŸ‘¤ **Actor:** `${{ github.actor }}`
            ğŸ•’ **Time:** `${{ github.event.head_commit.timestamp || github.event.created_at || github.run_started_at }}`
            ğŸ”— **Run:** [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            âœï¸ **Ref:** `${{ github.ref }}`
            ğŸ—‚ï¸ **Workflow:** `${{ github.workflow }}`
            ğŸ·ï¸ **Job:** `${{ github.job }}`
            
            ğŸš€ **Message:** An event of type `${{ github.event_name }}` was triggered by `${{ github.actor }}`.

            _This is an automated log message._ âš™ï¸
